In [1]:
print("jfahkjhfkasjhf")

jfahkjhfkasjhf


In [5]:
import graphviz

In [19]:
import numpy as np
tmp = [1,2,3]
a = np.array([1,2,3])
b = np.array([4,3,0])
print('A+B =',np.add(a,b))
print('A-B =',np.subtract(a,b))
print(a@a)

A+B = [5 5 3]
A-B = [-3 -1  3]
14


In [10]:
A = np.array([1,2,3])
print(np.multiply(A,A))

[1 4 9]


In [17]:
c = np.array([[1,2,3],
            [2,4,6]])
d = np.array([[1,1,1,4],
            [2,4,6,8],
             [3,4,5,6]])
print('dot',np.dot(c,d))
print(np.matmul(c,d))


dot [[14 21 28 38]
 [28 42 56 76]]
[[14 21 28 38]
 [28 42 56 76]]


#  你好啊
##
##
###


** 黑体 **

1. jkdaj
2. 几个重点
1. diyige
    * yige
    * liangeg
![dasdas](http://img62.ddimg.cn/2018/10/23/2018102317502374026.jpg)
<img src='http://img62.ddimg.cn/2018/10/23/2018102317502374026.jpg' , width=100>

$\pi$
$\sum_{i=1}^{i=n}$

$e {i\pi}+1

In [ ]:
import tensorflow as tf


插入表格

| diyilan | 2 | 3 |
|:----|:-----:|:----|
| das | das | fa |
|2452345432534 | 4523452345 | 35234523 |

In [6]:
print('\n'.join([' '.join(['%s*%s=%-2s' % (y, x, x*y) for y in range(1, x+1)]) for x in range(1, 10)]))

1*1=1 
1*2=2  2*2=4 
1*3=3  2*3=6  3*3=9 
1*4=4  2*4=8  3*4=12 4*4=16
1*5=5  2*5=10 3*5=15 4*5=20 5*5=25
1*6=6  2*6=12 3*6=18 4*6=24 5*6=30 6*6=36
1*7=7  2*7=14 3*7=21 4*7=28 5*7=35 6*7=42 7*7=49
1*8=8  2*8=16 3*8=24 4*8=32 5*8=40 6*8=48 7*8=56 8*8=64
1*9=9  2*9=18 3*9=27 4*9=36 5*9=45 6*9=54 7*9=63 8*9=72 9*9=81


In [7]:
4/4

1.0

In [5]:
"""dasdas
dasdas
dasdsa"""

'dasdas\ndasdas\ndasdsa'

In [11]:
type(1)

int

In [13]:
123,456,789

(123, 456, 789)

In [16]:
?type