#### 1. Builting a graph

In [2]:
import tensorflow as tf

In [12]:
a=tf.constant(1,name="input_a")
b=tf.constant(2,name="input_b")

In [5]:
c=tf.multiply(a,b, name='mul_c')
d=tf.multiply(a,b, name='mul_d')

In [7]:
e=tf.add(c,d, name='add_e')

In [8]:
print(e)

Tensor("add_e_1:0", shape=(), dtype=int32)


#### 2. Running a graph

In [10]:
sess = tf.Session()

In [11]:
sess.run(e)

4

In [37]:
writer = tf.summary.FileWriter('./my_graph',sess.graph)

In [14]:
writer.close()
sess.close()

In [5]:
!tensorboard --logdir = './my_graph'

'tensorboard' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


### More about Tensor?
#### 1. Tensor Shapes
#### 2. Tensor Operations
#### 3. Tensor Slicing
#### 4. Sequences

### More about Graph

## shapes

In [19]:
sess=tf.InteractiveSession()

In [21]:
x=tf.constant([[1,9,2,7],[3,3,6,6],[7,6,5,3],[1,9,1,9]])

In [22]:
x.eval()

array([[1, 9, 2, 7],
       [3, 3, 6, 6],
       [7, 6, 5, 3],
       [1, 9, 1, 9]])

In [23]:
tf.shape(x).eval()

array([4, 4])

## size

In [24]:
tf.size(x).eval()

16

## rank

In [27]:
x = tf.constant([[[1],[0]],[[3],[1]],[[7],[4]],[[1],[8]]])

In [28]:
tf.rank(x).eval()

3

In [29]:
#t[i, j, k]

In [31]:
x[3,1,0].eval()

8

### squeeze

In [33]:
x=tf.constant([[[1,9,2,7],[3,3,6,6],[7,6,5,3],[1,9,1,9]]])

In [35]:
tf.shape(x).eval()

array([1, 4, 4])

In [36]:
tf.rank(x).eval()

3

In [37]:
x.eval()

array([[[1, 9, 2, 7],
        [3, 3, 6, 6],
        [7, 6, 5, 3],
        [1, 9, 1, 9]]])

In [38]:
z = tf.squeeze(x).eval()

In [39]:
tf.shape(z).eval()

array([4, 4])

#### Expand dimension

In [42]:
x=tf.constant([[[1,9,2,7],[3,3,6,6],[7,6,5,3]],[[1,9,2,7],
                                                          [3,3,6,6],[7,6,5,3]]])

In [44]:
tf.shape(x).eval()

array([2, 3, 4])

In [45]:
z = tf.expand_dims(x,-2)

In [46]:
tf.shape(z).eval()

array([2, 3, 1, 4])

In [47]:
z.eval()

array([[[[1, 9, 2, 7]],

        [[3, 3, 6, 6]],

        [[7, 6, 5, 3]]],


       [[[1, 9, 2, 7]],

        [[3, 3, 6, 6]],

        [[7, 6, 5, 3]]]])

In [48]:
# 0  0th element expansion 2 to 1,2                   shape =[1,2,3,4]
# 1  1st element expansion 3 to 1,3                   shape =[2,1,3,4]
# 2  2nd element expansion 4 to 1,4                   shape =[2,3,1,4]
# 3  2nd element expansion 4 to 4,1                   shape =[2,3,4,1]
# -1 last element expansion 4 to 4,1                  shape =[2,3,4,1]
# -2 second last element expansion 3 to 3,1           shape =[2,3,1,4]
# -3 third last element expansion 2 to                shape =[2,1,3,4]
# -4 third last element expansion 2 to 1,2            shape =[1,2,3,4]

### More about Session

In [4]:
a=tf.constant(1,name="input_a")
b=tf.constant(2,name="input_b")

c=tf.add(a,b, name='add_c')

sess=tf.Session(graph =tf.get_default_graph())
sess.run(c)

3

In [6]:
#sess.run(fetches, feed_dict=None, options=None, run_metadata=None)

fetches 可以接收 tensor 或者 Tensor Object   Tensor 返回 numpy array   Tensor Object 返回 none 
feed_dict 可以改写 tensor 的值 常用于给模型赋予 x,y 值

In [9]:
a=tf.constant(1,name="input_a")
b=tf.constant(2,name="input_b")

c=tf.add(a,b, name='add_c')

a_new = {a: 10}

sess=tf.Session(graph =tf.get_default_graph())
sess.run(c, feed_dict = a_new)

12

In [10]:
sess.close()

### More about constant

In [12]:
a= tf.constant([1,2], name ='constant_a')
print (tf.get_default_graph().as_graph_def())

node {
  name: "input_a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "input_b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "add_c"
  op: "Add"
  input: "input_a"
  input: "input_b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "input_a_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "input_b_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      ty

### Variables

In [14]:
tf.Variable([2,1], name= 'var_0')

<tf.Variable 'var_0_1:0' shape=(2,) dtype=int32_ref>

In [15]:
random_variable= tf.Variable(tf.random_normal([2,2]), name= 'var_random')

In [17]:
tf.zeros([3,2])
tf.ones([3,2])
tf.random_normal([3,2],mean =0.0,stddev=1.0)
tf.truncated_normal([3,2],mean =0.0,stddev=1.0)

<tf.Tensor 'truncated_normal:0' shape=(3, 2) dtype=float32>

In [18]:
random_variable = tf.Variable(tf.random_normal([2,2]), name='var_random')
init = tf.variables_initializer([random_variable], name='random_variable')

sess = tf.Session()
sess.run(init)
sess.run(random_variable)

array([[-0.39282298, -0.07164392],
       [-0.57324237,  0.35543323]], dtype=float32)

In [20]:
#tf.Variable(trainable=True)

### More about Placeholders

In [21]:
import tensorflow as tf
import numpy as np

In [22]:
# tf.placeholder(dtype, shape=None, name=None)   #Required dtype

In [23]:
a = tf.placeholder(tf.int32,shape=[5],name='input_a')

In [24]:
b = tf.reduce_prod(a,name='input_b')

In [25]:
c = tf.add(b,b,name='input_c')


In [26]:
sess = tf.Session()

In [27]:
input_dict = {a:np.array([1,2,3,4,5])}

In [28]:
sess.run(c, feed_dict=input_dict)

240

In [29]:
sess.close()

### How to organize your graph?      name_scope

In [32]:
import tensorflow as tf
with tf.name_scope("A"):
    a = tf.add(1,2, name='a')
    b = tf.multiply(2,4, name='b')
    
with tf.name_scope("b"):
    c = tf.add(2,2, name='c')
    d = tf.multiply(3,2, name='d')
with tf.name_scope("output"):
    e = tf.add(b,c)
sess = tf.Session()
sess.run(e)
writer = tf.summary.FileWriter('./name_scope_example', sess.graph)
writer.close()
sess.close()

In [36]:
tf.summary.FileWriter?